name: _run-tests
on:
  workflow_call:
    inputs:
      marker:
        description: 'pytest -m expression (e.g., "basic", "integration", "not integration")'
        required: true
        type: string
    secrets: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # If set, uv will run without updating the uv.lock file. Equivalent to the `uv run --frozen`.
  UV_FROZEN: "1"

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/python-uv-setup
      - name: Run Ruff linter
        run: uv run ruff check .
      - name: Run Ruff formatter
        run: uv run ruff format --check .

  mypy:
    name: Mypy
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/python-uv-setup
      # Restore mypy cache to speed up the run
      - name: Restore mypy cache
        uses: actions/cache/restore@v4
        with:
          path: .mypy_cache
          key: mypy-cache-${{ hashFiles('pyproject.toml') }}

  test:
    name: Test "${{ inputs.marker }}"
    runs-on: ubuntu-24.04-arm
    # env:
    #   ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    #   GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
    #   OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    #   OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check architecture
        run: uname -m
      - name: Install dependencies
        uses: ./.github/actions/python-uv-setup
      - name: Sync for update
        run: uv sync --extra all
      - name: Run core tests
        run: uv run pytest -n auto -m "${{ inputs.marker }}" tests/
